---
- name: Installing package
  hosts: all
  become: true
  gather_facts: no
  tasks:
  - name: Installing the  package
    yum: 
      name: httpd
      state: present

  - name: Starting the httpd service
    service: 
      name: httpd 
      state: started
