---
- name: Installing Multiple packages using with_items condition
  hosts: all
  gather_facts: no
  become: true
  tasks:
  - name: Installing multiple packages
    yum: 
      name: "{{item}}"
      state: installed
    with_items:
      - make
      - gzip
      - tree
      - git  
